project:
  type: website

website:
  title: "Jackson Murphy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

